name: Arduino CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Arduino CLI
      uses: per1234/setup-arduino@v1
      with:
        arduino-cli-version: latest

    - name: Install dependencies
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32
        arduino-cli lib install "https://github.com/kostko/arduino-crypto.git"

    - name: Compile Sketch
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32 CryptoSignAuthenticatorTest

    - name: Run unit tests
      run: |
        arduino-cli upload --fqbn esp32:esp32:esp32 --port /dev/ttyUSB0 CryptoSignAuthenticatorTest

